# Generated by Django 5.0.3 on 2024-04-29 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.CharField(default=datetime.date.today, max_length=155),
        ),
    ]
